# Generated by Django 5.0.6 on 2024-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/avatar.png', upload_to='images/'),
        ),
    ]
